# Generated by Django 4.2.3 on 2023-07-13 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('role_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.department')),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.role')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.employee')),
            ],
        ),
    ]
